#
# Makefile for TI's shared transport line discipline
# and its protocol drivers (BT, FM, GPS)
#
obj-$(CONFIG_ZTE_SENSORS_ACCEL_KXTF9)		+=kxtik.o
# added by yangze 20120919
obj-$(CONFIG_ZTE_SENSORS_ACCEL_KIONIX)		+=kionix_accel.o
obj-$(CONFIG_ZTE_SENSORS_ACCEL_LIS3DH) 		+= lis3dh_acc.o
obj-$(CONFIG_ZTE_SENSORS_GYRO_L3G4200D) 	+= l3g4200d_gyr.o
obj-$(CONFIG_ZTE_SENSORS_GYRO_MPU3050) 		+= mpu3050.o
obj-$(CONFIG_ZTE_SENSORS_CAP_PROX_SX9500) 	+= sx95xx.o sx9500.o
obj-$(CONFIG_ZTE_SENSORS_ATTINY44A)         += attiny44a.o
obj-$(CONFIG_ZTE_SENSORS_COMPASS_AK8963)	+= akm8963.o
obj-$(CONFIG_ZTE_SENSORS_COMPASS_AK09911)	+= akm09911.o
