ccflags-y += -Idrivers/media/platform/msm/camera_v2_zte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zte/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zte/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
